spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: hotdeal
      # 배포 시에만
#      username: taptorestart
#      password: thisispass
#      authentication-database: admin

  batch:
    job:
      names: ${job.name:NONE}

  main:
    web-application-type: none
