spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: hotdeal

  batch:
    job:
      names: ${job.name:AliExpressJob}

#  main:
#    allow-bean-definition-overriding: true
#      배포할 경우에만
#      username: taptorestart
#      password: thisispass
#      authentication-database: admin